Vagrant.configure('2') do |config|

  # Box
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.hostname = 'ruby-vm.adlawson'

  # Shared folders
  config.vm.synced_folder '.', '/srv'

  # Setup
  config.vm.provision :shell, :inline => 'apt-get update --fix-missing'
  config.vm.provision :shell, :inline => 'apt-get install -q -y cowsay python-software-properties python g++ make git curl'
  config.vm.provision :shell, :inline => 'curl -L https://get.rvm.io | bash -s stable'
  config.vm.provision :shell, :inline => 'rvm install 2.0.0 --latest-binary --autolibs=enabled && rvm --fuzzy alias create default 2.0.0'

  # Done
  config.vm.provision :shell, :inline => 'cowsay "Your virtual machine is ready!"'

  # VirtualBox
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--name', 'adlawson.vm.ruby']
  end

end