# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Shared folders
  config.vm.synced_folder ".", "/srv"

  # Setup
  config.vm.provision :shell, :inline => "apt-get update --fix-missing"
  config.vm.provision :shell, :inline => "apt-get install -q -y python-software-properties python g++ make git curl"
  config.vm.provision :shell, :inline => "wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
  config.vm.provision :shell, :inline => "dpkg -i erlang-solutions_1.0_all.deb"
  config.vm.provision :shell, :inline => "apt-get update && apt-get install erlang -q -y"

  # Done
  config.vm.provision :shell, :inline => "cowsay \"Your development environment is ready!\""

end
