# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Elixir version
  version = "v0.12.2"

  # Box
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Shared folders
  config.vm.synced_folder ".", "/srv"

  # Setup
  config.vm.provision :shell, :inline => "apt-get update --fix-missing"
  config.vm.provision :shell, :inline => "apt-get install -q -y cowsay python-software-properties python g++ make git curl"
  config.vm.provision :shell, :inline => "wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
  config.vm.provision :shell, :inline => "dpkg -i erlang-solutions_1.0_all.deb"
  config.vm.provision :shell, :inline => "apt-get update && apt-get install erlang -q -y"
  config.vm.provision :shell, :inline => "git clone git://github.com/elixir-lang/elixir.git && cd elixir && git checkout v0.12.2 && make && make install"
  config.vm.provision :shell, :inline => "cd /home/vagrant/elixir && git checkout #{version}"
  config.vm.provision :shell, :inline => "cd /home/vagrant/elixir && make && make install"

  # Done
  config.vm.provision :shell, :inline => "cowsay \"Your development environment is ready!\""

end
