# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    hostname = "elixir.box"
    locale = "en_GB.UTF.8"

    # Box
    config.vm.box = "trusty64"
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/1/providers/virtualbox.box"

    # Shared folders
    config.vm.synced_folder ".", "/srv"

    # Setup
    config.vm.provision :shell, :inline => "touch .hushlogin"
    config.vm.provision :shell, :inline => "hostname #{hostname} && locale-gen #{locale}"
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :shell, :inline => "apt-get install -q -y g++ make git curl vim"

    # Lang
    config.vm.provision :shell, :inline => "echo 'fetching erlang' && wget -q http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
    config.vm.provision :shell, :inline => "dpkg -i erlang-solutions_1.0_all.deb"
    # config.vm.provision :shell, :inline => "apt-get update && apt-get install -q -y erlang"
    config.vm.provision :shell, :inline => "apt-get update && apt-get install -q -y elixir"
    # config.vm.provision :shell, :inline => "git clone git://github.com/elixir-lang/elixir.git"
    # config.vm.provision :shell, :inline => "git clone git://github.com/rebar/rebar.git && cd rebar && make"
    # config.vm.provision :shell, :inline => "cd /home/vagrant/elixir && git checkout #{version}"
    # config.vm.provision :shell, :inline => "cd /home/vagrant/elixir && make && make install"
    # config.vm.provision :shell, :inline => "ln -s /home/vagrant/rebar/rebar /usr/local/bin/rebar"

end
