# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    hostname = "clojure.box"
    locale = "en_GB.UTF.8"

    # Box
    config.vm.box = "ubuntu/trusty64"

    # Shared folders
    config.vm.synced_folder ".", "/srv"

    # Setup
    config.vm.provision :shell, :inline => "touch .hushlogin"
    config.vm.provision :shell, :inline => "hostname #{hostname} && locale-gen #{locale}"
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :shell, :inline => "apt-get install -q -y g++ make git curl vim"

    # Lang
    config.vm.provision :shell, :inline => "add-apt-repository -y ppa:webupd8team/java && apt-get update"
    config.vm.provision :shell, :inline => "echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections"
    config.vm.provision :shell, :inline => "echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections"
    config.vm.provision :shell, :inline => "apt-get install -q -y oracle-java8-installer"
    config.vm.provision :shell, :inline => "echo 'fetching leiningen/stable' && wget -q https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    config.vm.provision :shell, :inline => "mv lein /usr/local/bin/lein && chmod a+x /usr/local/bin/lein"

    # Virtualbox
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

end
