# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Shared folders
  config.vm.synced_folder ".", "/srv"

  # Setup
  config.vm.provision :shell, :inline => "apt-get update --fix-missing"
  config.vm.provision :shell, :inline => "apt-get install -q -y cowsay python-software-properties python g++ make git curl openjdk-7-jre-headless"
  config.vm.provision :shell, :inline => "wget https://go.googlecode.com/files/go1.2.linux-amd64.tar.gz"
  config.vm.provision :shell, :inline => "wget https://raw.github.com/technomancy/leiningen/stable/bin/lein"
  config.vm.provision :shell, :inline => "mv lein /usr/local/bin/lein && chmod +x /usr/local/bin/lein"
  config.vm.provision :shell, :inline => "/usr/local/bin/lein version"

  # Done
  config.vm.provision :shell, :inline => "cowsay \"Your development environment is ready!\""

end
